#!/bin/bash

# ==============================================================================
#  lazydeb.sh (Version 4)
#  A script to fully automate system and Flatpak updates on Debian-based
#  systems. Ensures contrib & non-free are enabled and installs Flatpak
#  if needed.
# ==============================================================================

# Exit immediately if a command fails
set -e

# Check if the script is run as root
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root. Please use 'sudo'." >&2
  exit 1
fi

echo "### Starting the automatic maintenance setup ###"

# --- Part 1: Set up Unattended Upgrades for the Debian system ---

echo
echo "--- [1/2] Configuring unattended-upgrades for the base system ---"

# NEW: Ensure contrib, non-free, and non-free-firmware are enabled
echo "INFO: Checking and enabling contrib, non-free & non-free-firmware repos..."
# Creates a backup of the original file (.bak)
# Searches for lines starting with "deb" that contain "main" but not yet "contrib"
# and then appends the additional components.
sed -i.bak \
    -e 's/^\(deb.* main\)$/\1 contrib non-free non-free-firmware/' \
    -e 's/^\(deb-src.* main\)$/\1 contrib non-free/' \
    /etc/apt/sources.list

echo "INFO: sources.list has been updated."

# Install required packages
apt-get update
apt-get install -y unattended-upgrades apt-listchanges

# Enable and configure automatic updates
echo "INFO: Creating configuration for automatic APT updates..."
tee /etc/apt/apt.conf.d/20auto-upgrades > /dev/null <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
APT::Unattended::Remove-Unused-Dependencies "true";
APT::Unattended::Remove-Unused-Kernel-Packages "true";
EOF

# Define which update sources will be used
echo "INFO: Defining the update origins for unattended-upgrades..."
tee /etc/apt/apt.conf.d/50unattended-upgrades > /dev/null <<'EOF'
// Automatically generated by debian-autoupdate.sh
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
    "${distro_id}:${distro_codename}-updates";
};

Unattended-Upgrade::Remove-Unused-Dependencies "true";
EOF

# Ensure the systemd timers for APT are running
echo "INFO: Enabling and starting APT timers..."
systemctl enable --now apt-daily.timer
systemctl enable --now apt-daily-upgrade.timer

echo "SUCCESS: Unattended-upgrades for the Debian system are now active."

# --- Part 2: Set up automatic Flatpak updates and cleanup ---

echo
echo "--- [2/2] Configuring systemd timer for Flatpaks ---"

# Check if Flatpak is installed. If not, install it.
if ! command -v flatpak &> /dev/null; then
    echo "INFO: Flatpak is not installed. Installing it now..."
    apt-get install -y flatpak
    echo "INFO: Adding the Flathub repository to access apps..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    echo "INFO: Flatpak has been successfully installed and configured."
fi

# Create the service file for the systemd timer
echo "INFO: Creating systemd service for Flatpak updates..."
tee /etc/systemd/system/flatpak-update.service > /dev/null <<'EOF'
[Unit]
Description=Update all Flatpaks and remove unused runtimes
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/flatpak update --assumeyes
ExecStartPost=/usr/bin/flatpak uninstall --unused --assumeyes
EOF

# Create the timer file for the systemd timer
echo "INFO: Creating systemd timer for daily execution..."
tee /etc/systemd/system/flatpak-update.timer > /dev/null <<'EOF'
[Unit]
Description=Run flatpak-update.service daily to update all Flatpaks

[Timer]
OnCalendar=daily
RandomizedDelaySec=4h
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Reload systemd and enable the new timer
echo "INFO: Enabling and starting the Flatpak timer..."
systemctl daemon-reload
systemctl enable --now flatpak-update.timer

echo "SUCCESS: Flatpak updates and cleanup are now automated."
echo

# --- Finalization ---
echo "#####################################################################"
echo "#                        AUTOMATION IS ACTIVE                       #"
echo "#####################################################################"
echo "# Your system will now update itself automatically.               #"
echo "# Debian updates (incl. non-free & contrib) will be applied     #"
echo "# daily in the background. Flatpak updates as well.             #"
echo "#####################################################################"
